"""
Extended Thinking Mode Inference Engine.

Implements the full thinking pipeline:

    ┌─────────────────────────────────────────────────────────────┐
    │ INPUT: user prompt                                          │
    │                                                             │
    │  [PREFILL]                                                  │
    │  Prepend:  <|start_header|>assistant<|end_header|>          │
    │            <thinking>\\n                                     │
    │                                                             │
    │  [THINKING PHASE]                                           │
    │  Generate thinking tokens until stop criterion met          │
    │  - Entropy-based early stopping                             │
    │  - Token budget (mode-dependent)                            │
    │  - </thinking> token generated by model                     │
    │  - Compaction at 30K tokens (context summarization)         │
    │                                                             │
    │  [THINKING REDACTION]                                       │
    │  Thinking tokens removed from context                       │
    │  Replaced by ~5-token placeholder: <redacted_thinking/>     │
    │  (Never shown to user; not part of cacheable prefix)        │
    │                                                             │
    │  [OUTPUT PHASE]                                             │
    │  Standard autoregressive decode of final response           │
    │                                                             │
    │ OUTPUT: response tokens (no thinking visible)               │
    └─────────────────────────────────────────────────────────────┘

Key properties:
    - Thinking tokens billed at output rate ($25/M)
    - Thinking tokens CANNOT be part of prompt cache prefix
    - Model sees its own thinking during output generation
    - Thinking is deterministic given same seed + prompt
    - Budget forcing: model guaranteed to generate ≥ min_tokens thinking
      (prevents "lazy" short-circuit on hard problems)

Compaction (at ~30K thinking tokens):
    - Triggered when thinking approaches context limit
    - A separate call summarizes thinking so far to ~2K tokens
    - Only ~5% of responses trigger this (long reasoning chains)
    - Adds ~$0.05 overhead for the summarization call

References:
    - Anthropic "Extended Thinking" API docs (2025)
    - "Let Me Think" / o1-style reasoning traces
    - Budget forcing: Muennighoff et al. 2025 (s1 paper)
"""

import time
import torch
import torch.nn.functional as F
from typing import Iterator, Optional, List, Tuple, Dict, Any

from ..model.transformer import ClaudeModel
from .fast_mode import (
    ThinkingMode, ThinkingBudget, ThinkingStopCriterion,
    KVCache, FastModeEngine
)


# ---------------------------------------------------------------------------
# Thinking Context Compactor
# ---------------------------------------------------------------------------

class ThinkingCompactor:
    """
    Summarizes accumulated thinking tokens when they exceed the compaction
    threshold (~30K tokens).

    Process:
        1. Collect all thinking tokens so far
        2. Call a small summarization model (or Claude itself with special prompt)
        3. Replace thinking prefix in KV cache with summary
        4. Continue thinking from the compressed state

    This prevents the KV cache from exceeding 1M tokens during complex
    reasoning tasks that require many steps.

    In practice, only ~5% of high/max thinking mode responses trigger this.
    """

    SUMMARIZE_PROMPT = (
        "The following is an incomplete chain of thought reasoning. "
        "Summarize the key conclusions reached so far in 500 words or less, "
        "preserving all derived facts, hypotheses, and current focus:\n\n"
        "{thinking_text}\n\nSummary:"
    )

    def __init__(self, summarizer_model, tokenizer):
        self.summarizer = summarizer_model
        self.tokenizer  = tokenizer

    def compact(
        self, thinking_tokens: List[int]
    ) -> Tuple[str, List[int]]:
        """
        Summarize thinking_tokens and return compact representation.

        Args:
            thinking_tokens: list of token IDs from thinking phase

        Returns:
            summary_text  : plain text summary
            summary_ids   : token IDs of the summary
        """
        thinking_text = self.tokenizer.decode(
            thinking_tokens, skip_special_tokens=True
        )
        prompt = self.SUMMARIZE_PROMPT.format(thinking_text=thinking_text)

        summary_ids_tensor = self.tokenizer.encode(
            prompt, return_tensors="pt"
        )

        with torch.inference_mode():
            out = self.summarizer.generate(
                summary_ids_tensor,
                max_new_tokens=512,
                temperature=0.3,   # Low temp for faithful summarization
            )

        # Extract only the new tokens (the summary)
        summary_ids = out[0, summary_ids_tensor.shape[1]:].tolist()
        summary_text = self.tokenizer.decode(
            summary_ids, skip_special_tokens=True
        )

        return summary_text, summary_ids


# ---------------------------------------------------------------------------
# Thinking Mode Engine
# ---------------------------------------------------------------------------

class ThinkingModeEngine(FastModeEngine):
    """
    Extended thinking inference engine.

    Extends FastModeEngine with:
        1. Thinking phase prefix injection
        2. Token budget enforcement
        3. Entropy-based early stopping
        4. Thinking token redaction between turns
        5. Context compaction for long thinking chains

    Token format during thinking:
        <|start_header|>assistant<|end_header|>
        <thinking>
        [thinking tokens — internal monologue]
        </thinking>
        [output tokens — visible response]
        <|eot_id|>

    The <thinking>...</thinking> block is:
        - Visible to model during BOTH thinking and output phases
        - Hidden from user (API returns only output tokens)
        - Billed at output rate ($25/M tokens)
        - NOT cacheable as prompt prefix
        - Replaced by 5-token placeholder in subsequent turns
    """

    # Special token strings
    THINKING_START_STR = "<thinking>"
    THINKING_END_STR   = "</thinking>"

    def __init__(self, *args, compactor: Optional[ThinkingCompactor] = None, **kwargs):
        super().__init__(*args, **kwargs)
        self.compactor = compactor

        # Resolve thinking token IDs
        self.thinking_start_id = self.tokenizer.convert_tokens_to_ids(
            self.THINKING_START_STR
        )
        self.thinking_end_id = self.tokenizer.convert_tokens_to_ids(
            self.THINKING_END_STR
        )

        # Placeholder token sequence for redacted thinking
        # Replaces entire thinking block in subsequent turns: ~5 tokens
        self.thinking_placeholder = self.tokenizer.encode(
            "<redacted_thinking/>", add_special_tokens=False
        )

    @torch.inference_mode()
    def generate_with_thinking(
        self,
        prompt: str,
        thinking_mode: ThinkingMode = ThinkingMode.MEDIUM,
        max_new_tokens: int = 2048,
        temperature: float = 1.0,
        top_p: float = 0.95,
        top_k: int = 50,
        stream_output: bool = True,
        stream_thinking: bool = False,   # expose thinking to caller?
    ) -> Iterator[Dict[str, Any]]:
        """
        Generate with extended thinking.

        Args:
            prompt          : user prompt
            thinking_mode   : one of FAST, LOW, MEDIUM, HIGH, MAX
            max_new_tokens  : max output tokens (not counting thinking)
            temperature     : sampling temperature
            top_p, top_k    : sampling params
            stream_output   : stream output tokens as generated
            stream_thinking : if True, also yield thinking tokens
                              (for debugging; not exposed via API)

        Yields dicts with keys:
            "type"     : "thinking" | "output" | "stats"
            "token"    : decoded token string
            "token_id" : integer token ID
            For "stats":
                "thinking_tokens" : int
                "output_tokens"   : int
                "thinking_ms"     : float
                "output_ms"       : float
                "total_ms"        : float
        """
        # Fast mode: skip thinking entirely
        if thinking_mode == ThinkingMode.FAST:
            for token_text in self.generate(
                prompt, max_new_tokens, temperature, top_p, top_k, stream_output
            ):
                yield {"type": "output", "token": token_text}
            return

        t_start = time.perf_counter()

        # --- Tokenize prompt ---
        input_ids = self.tokenizer.encode(
            prompt, return_tensors="pt"
        ).to(self.device)

        # --- Inject thinking start tokens ---
        thinking_prefix_ids = self.tokenizer.encode(
            "\n<thinking>\n",
            add_special_tokens=False,
            return_tensors="pt"
        ).to(self.device)
        current_ids = torch.cat([input_ids, thinking_prefix_ids], dim=1)

        # --- Budget & stop criterion ---
        budget   = ThinkingBudget.for_mode(thinking_mode)
        stopper  = ThinkingStopCriterion(budget, self.thinking_end_id)

        kv_cache = KVCache(
            num_layers=self.config.num_hidden_layers,
            device=self.device,
        )

        # ----------------------------------------------------------------
        # PHASE 1: THINKING
        # ----------------------------------------------------------------
        thinking_tokens: List[int] = []
        t_thinking_start = time.perf_counter()

        while True:
            # Run target model for one thinking token
            outputs = self.model(
                current_ids,
                past_key_values=[kv_cache.get(i)
                                 for i in range(self.config.num_hidden_layers)],
                use_cache=True,
            )
            if outputs.get("past_key_values"):
                for i, kv in enumerate(outputs["past_key_values"]):
                    if kv is not None:
                        kv_cache.update(i, kv[0], kv[1])

            logits    = outputs["logits"][0, -1, :]   # [vocab_size]
            token_id  = self._sample(logits, temperature, top_p, top_k)

            thinking_tokens.append(token_id)

            if stream_thinking:
                token_text = self.tokenizer.decode(
                    [token_id], skip_special_tokens=False
                )
                yield {"type": "thinking", "token": token_text,
                       "token_id": token_id}

            # Check stop criterion
            if stopper.should_stop(token_id, logits):
                break

            # Compaction check
            if stopper.needs_compaction() and self.compactor:
                summary_text, summary_ids = self.compactor.compact(
                    thinking_tokens
                )
                # Reset: replace thinking tokens with summary
                thinking_tokens = summary_ids
                # Rebuild KV cache with compressed thinking prefix
                kv_cache.clear()
                summary_tensor = torch.tensor(
                    [[self.thinking_start_id] + summary_ids],
                    device=self.device
                )
                current_ids = torch.cat([input_ids, summary_tensor], dim=1)
                stopper.tokens_generated = len(summary_ids)
                continue

            # Extend context for next thinking step
            current_ids = torch.tensor(
                [[token_id]], device=self.device, dtype=torch.long
            )

        t_thinking_ms = (time.perf_counter() - t_thinking_start) * 1000

        # Ensure thinking ends with </thinking> token
        if thinking_tokens and thinking_tokens[-1] != self.thinking_end_id:
            # Force close the thinking block
            end_ids = self.tokenizer.encode(
                "\n</thinking>\n", add_special_tokens=False
            )
            for tid in end_ids:
                thinking_tokens.append(tid)

        # ----------------------------------------------------------------
        # PHASE 2: OUTPUT GENERATION
        # (Model has seen its own thinking; now generates final response)
        # ----------------------------------------------------------------
        output_tokens: List[int] = []
        t_output_start = time.perf_counter()

        # The KV cache now contains: [prompt] + [thinking tokens]
        # We generate the output response continuing from this context
        # Use a single token to continue generation from cache
        current_ids = torch.tensor(
            [[thinking_tokens[-1] if thinking_tokens else self.bos_token_id]],
            device=self.device, dtype=torch.long
        )

        for _ in range(max_new_tokens):
            outputs = self.model(
                current_ids,
                past_key_values=[kv_cache.get(i)
                                 for i in range(self.config.num_hidden_layers)],
                use_cache=True,
            )
            if outputs.get("past_key_values"):
                for i, kv in enumerate(outputs["past_key_values"]):
                    if kv is not None:
                        kv_cache.update(i, kv[0], kv[1])

            logits   = outputs["logits"][0, -1, :]
            token_id = self._sample(logits, temperature, top_p, top_k)

            if token_id == self.eos_token_id:
                break

            output_tokens.append(token_id)

            if stream_output:
                token_text = self.tokenizer.decode(
                    [token_id], skip_special_tokens=True
                )
                yield {"type": "output", "token": token_text,
                       "token_id": token_id}

            current_ids = torch.tensor(
                [[token_id]], device=self.device, dtype=torch.long
            )

        t_output_ms = (time.perf_counter() - t_output_start) * 1000
        t_total_ms  = (time.perf_counter() - t_start) * 1000

        if not stream_output:
            full_text = self.tokenizer.decode(
                output_tokens, skip_special_tokens=True
            )
            yield {"type": "output", "token": full_text}

        # ----------------------------------------------------------------
        # STATS (billing info, latency)
        # ----------------------------------------------------------------
        yield {
            "type":             "stats",
            "thinking_tokens":  len(thinking_tokens),
            "output_tokens":    len(output_tokens),
            "thinking_ms":      t_thinking_ms,
            "output_ms":        t_output_ms,
            "total_ms":         t_total_ms,
            "ttft_ms":          t_thinking_ms,   # first output token after thinking
            "thinking_mode":    thinking_mode.value,
            # Cost estimate (at $25/M for output + thinking)
            "cost_usd":         (len(thinking_tokens) + len(output_tokens))
                                * 25 / 1_000_000,
        }

    def redact_thinking(
        self, conversation_history: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """
        Prepare conversation history for the next turn by redacting thinking.

        Thinking tokens from previous turns are:
          1. Removed from context
          2. Replaced by a fixed ~5-token placeholder

        This ensures:
          - Context window not wasted on previous thinking
          - Model cannot "fake" past thinking in subsequent turns
          - Thinking cannot be used as a cacheable prefix

        Args:
            conversation_history: list of {"role": ..., "content": ...}
                                  where assistant turns may contain thinking

        Returns:
            cleaned history with thinking blocks replaced by placeholders
        """
        cleaned = []
        placeholder = self.tokenizer.decode(
            self.thinking_placeholder, skip_special_tokens=False
        )

        for turn in conversation_history:
            if turn["role"] == "assistant" and "<thinking>" in turn.get("content", ""):
                # Extract content outside thinking blocks
                content = turn["content"]
                start   = content.find("<thinking>")
                end     = content.find("</thinking>")
                if start != -1 and end != -1:
                    # Replace thinking block with placeholder
                    before  = content[:start]
                    after   = content[end + len("</thinking>"):]
                    content = before + placeholder + after
                cleaned.append({**turn, "content": content})
            else:
                cleaned.append(turn)

        return cleaned
